Avoid global `Logger` as this conflicts with a native class in Godot 4.5
Fixes https://github.com/bitwes/Gut/issues/709

ERROR: res://addons/gut/utils.gd:95 - Parse Error: The member "Logger" shadows a native class.